name: deploy-prod
on: workflow_dispatch

jobs:
  deploy-on-dev:
    name: 'Deploy on Production'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Prepare Node Environment
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.PROD_SSH_KEY }}
          name: id_rsa
          known_hosts: ${{ secrets.PROD_KNOWN_HOSTS }}
      - name: Cache node modules
        id: cache-node-modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: node_modules-${{ hashFiles('package.json') }}
      - name: project update on server
        run: |
          ssh -tt ${{ env.PROD_SSH_USERNAME }}@${{ env.PROD_SSH_HOST }} -p ${{ env.PROD_SSH_PORT }} "cd ${{ env.PROD_PROJECT_PATH }}; git reset --hard; git pull; exit;"
        env:
          PROD_SSH_PORT: ${{ secrets.PROD_SSH_PORT}}
          PROD_SSH_USERNAME: ${{ secrets.PROD_SSH_USERNAME }}
          PROD_SSH_HOST: ${{ secrets.PROD_SSH_HOST }}
          PROD_PROJECT_PATH: ${{ secrets.PROD_PROJECT_PATH }}
      - name: Install node modules on server
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: |
          ssh -tt ${{ env.PROD_SSH_USERNAME }}@${{ env.PROD_SSH_HOST }} -p ${{ env.PROD_SSH_PORT }} "cd ${{ env.PROD_PROJECT_PATH }}; rm -r node_modules/; rm  package-lock.json;bash -ic 'npm i --only=production;'; exit;"
        env:
          PROD_SSH_PORT: ${{ secrets.PROD_SSH_PORT}}
          PROD_SSH_USERNAME: ${{ secrets.PROD_SSH_USERNAME }}
          PROD_SSH_HOST: ${{ secrets.PROD_SSH_HOST }}
          PROD_PROJECT_PATH: ${{ secrets.PROD_PROJECT_PATH }}
      - name: Restart server processes
        run: |
          ssh -tt ${{ env.PROD_SSH_USERNAME }}@${{ env.PROD_SSH_HOST }} -p ${{ env.PROD_SSH_PORT }} "cd ${{ env.PROD_PROJECT_PATH }}; bash -ic 'pm2 restart ecosystem.config.js --only trad-prod;'; exit;"
        env:
          PROD_SSH_PORT: ${{ secrets.PROD_SSH_PORT}}
          PROD_SSH_USERNAME: ${{ secrets.PROD_SSH_USERNAME }}
          PROD_SSH_HOST: ${{ secrets.PROD_SSH_HOST }}
          PROD_PROJECT_PATH: ${{ secrets.PROD_PROJECT_PATH }}