name: deploy-dev
on:
  push:
    branches:
      - 'development'

jobs:
  deploy-on-dev:
    name: 'Deploy on development'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Prepare Node Environment
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.DEV_SSH_KEY }}
          name: id_rsa
          known_hosts: ${{ secrets.DEV_KNOWN_HOSTS }}
      - name: Cache node modules
        id: cache-node-modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: node_modules-${{ hashFiles('package.json') }}
      - name: project update on server
        run: |
          ssh -tt ${{ env.DEV_SSH_USERNAME }}@${{ env.DEV_SSH_HOST }} -p ${{ env.DEV_SSH_PORT }} "cd ${{ env.DEV_PROJECT_PATH }}; git reset --hard; git pull; exit;"
        env:
          DEV_SSH_PORT: ${{ secrets.DEV_SSH_PORT}}
          DEV_SSH_USERNAME: ${{ secrets.DEV_SSH_USERNAME }}
          DEV_SSH_HOST: ${{ secrets.DEV_SSH_HOST }}
          DEV_PROJECT_PATH: ${{ secrets.DEV_PROJECT_PATH }}
      - name: NPM install on server
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: |
          ssh -tt ${{ env.DEV_SSH_USERNAME }}@${{ env.DEV_SSH_HOST }} -p ${{ env.DEV_SSH_PORT }} "cd ${{ env.DEV_PROJECT_PATH }}; rm -r node_modules/; rm  package-lock.json;bash -ic 'npm i --only=production;'; exit;"
        env:
          DEV_SSH_PORT: ${{ secrets.DEV_SSH_PORT}}
          DEV_SSH_USERNAME: ${{ secrets.DEV_SSH_USERNAME }}
          DEV_SSH_HOST: ${{ secrets.DEV_SSH_HOST }}
          DEV_PROJECT_PATH: ${{ secrets.DEV_PROJECT_PATH }}
      - name: Restart server processes
        run: |
          ssh -tt ${{ env.DEV_SSH_USERNAME }}@${{ env.DEV_SSH_HOST }} -p ${{ env.DEV_SSH_PORT }} "cd ${{ env.DEV_PROJECT_PATH }}; bash -ic 'pm2 restart ecosystem.config.js --only trad-dev;'; exit;"
        env:
          DEV_SSH_PORT: ${{ secrets.DEV_SSH_PORT}}
          DEV_SSH_USERNAME: ${{ secrets.DEV_SSH_USERNAME }}
          DEV_SSH_HOST: ${{ secrets.DEV_SSH_HOST }}
          DEV_PROJECT_PATH: ${{ secrets.DEV_PROJECT_PATH }}
