name: TRAD deploy-test
on:
  push:
    branches:
      - 'staging'

jobs:
  deploy-on-test:
    name: 'Deploy on test'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Prepare Node Environment
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.TEST_SSH_HOST }}
          username: ${{ secrets.TEST_SSH_USERNAME }}
          password: ${{ secrets.TEST_AUTH_PASS }}
          port: ${{ secrets.TEST_SSH_PORT }}
          fingerprint: ${{ secrets.TEST_KNOWN_HOSTS }}
          script: |
            ls
#            Update the Project code
            cd ${{ env.TEST_PROJECT_PATH }}
            git reset --hard
            git pull
#            Install the packages
            rm -r node_modules/ package-lock.json
            bash -ic 'npm i --only=production'
#            Restart the Node Service
            bash -ic 'pm2 restart ecosystem.config.js --only trad-test'
      - name: Cache node modules
        id: cache-node-modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: node_modules-${{ hashFiles('package.json') }}
